### ISSUE TITLE
Request to Add New ETH Coin to the Game

### ISSUE THREAD

**Issue by HunterStile** [Przemek031/RollercoinBot#1]
Dear Przemek031,

I hope this message finds you well. I am writing to express my appreciation for your amazing project. I have been enjoying the game and the unique elements it offers.

I recently noticed that there is a new ETH coin in the game. However, it seems that this coin is not yet recognized by the current version of the script. Could you please update the project to include the new ETH coin? This addition would greatly enhance the gaming experience for all users.

Here are the details of the new coin:

Coin Type: ETH
RGB Values: [Please insert the correct RGB values you identified]
Your efforts and contributions to this project are highly valued, and I look forward to seeing this new feature implemented. Thank you for your time and consideration.

Best regards,
Hunterstile

**Comment by Przemek031** [comment]
I'm very glad that you like the bot, I just added a new coin. If you find new problems I will be happy to correct them. (I use rgb(66,105,207) eth for identification, I also corrected the comments). Once again, I'm very pleased that you like the bot.
